name: Python Greetings Pipeline

on:
  workflow_dispatch:

jobs:
  install-pip-deps:
    runs-on: self-hosted
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Checkout python-greetings repository
        uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          path: python-greetings

      - name: Installing all required dependencies...
        working-directory: python-greetings
        run: |
          echo Installing all required dependencies...
          python -m pip install -r requirements.txt

  deploy-to-dev:
    runs-on: self-hosted
    needs: install-pip-deps
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Clone python-greetings repo
        uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          path: python-greetings

      - name: Stop existing app process (optional, mock)
        run: echo "Skipping pm2 stop - using Start-Process instead"

      - name: Start python-greetings app on port 7001 without pm2
        working-directory: python-greetings
        shell: powershell
        run: |
          Start-Process python -ArgumentList "app.py", "--port", "7001"
