name: Python Greetings Pipeline

on:
  workflow_dispatch:

jobs:
  install-pip-deps:
    runs-on: self-hosted
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Checkout python-greetings repository
        uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          path: python-greetings

      - name: Installing all required dependencies...
        working-directory: python-greetings
        run: |
          echo Installing all required dependencies...
          pip install -r requirements.txt
